// * AUTH ACTION TYPE
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SET_REDIRECT_PATH = "AUTH_SET_REDIRECT_PATH";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_START_SIGN_UP = "AUTH_START_SIGN_UP";
export const AUTH_SIGN_UP_SUCCESS = "AUTH_SIGN_UP_SUCCESS";
export const AUTH_SIGN_UP_FAIL = "AUTH_SIGN_UP_FAIL";
export const AUTH_SET_USER_INFO = "AUTH_SET_USER_INFO";
export const AUTH_SET_USER_ROLE = "AUTH_SET_USER_ROLE";

// * PROJECT ACTION TYPE
export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";
export const DELETE_PROJECTS_START = "DELETE_PROJECTS_START";
export const DELETE_PROJECTS_SUCCESS = "DELETE_PROJECTS_SUCCESS";
export const DELETE_PROJECTS_FAIL = "DELETE_PROJECTS_FAIL";
export const GET_TRACKING_TIME = "GET_TRACKING_TIME";

// * TASK ACTION TYPE
export const FETCH_TASKS_START = "FETCH_TASKS_START";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAIL = "FETCH_TASKS_FAIL";
export const SELECT_TASK = "SELECTED_TASK";

// * TASK ACTION TYPE
export const TIME_START = "TIME_START";
export const TIME_END = "TIME_END";
export const TIME_CREATE = "TIME_CREATE";
export const TIME_EDIT = "TIME_EDIT";
export const TIME_SET_INTERVAL_ID = "TIME_SET_INTERVAL_ID";
export const STOP_COUNTING_TIME = "STOP_COUNTING_TIME";
export const INCREASE_TIME = "INCREASE_TIME";
export const START_SAVING_TIME = "START_SAVING_TIME";
export const SAVING_TIME_SUCCESS = "SAVING_TIME_SUCCESS";
export const SAVING_TIME_FAIL = "SAVING_TIME_FAIL";

// * TIMES ACTION TYPE
export const FETCH_TIMES_START = "FETCH_TIMES_START";
export const FETCH_TIMES_SUCCESS = "FETCH_TIMES_SUCCESS";
export const FETCH_TIMES_FAIL = "FETCH_TIMES_FAIL";
export const SELECT_TIME = "SELECT_TIME";

// * MEMBERS ACTION TYPE
export const LOADING = "LOADING";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const MEMBERS_ACTION_FAIL = "ACTION_FAIL";
export const SELECT_MEMBER = "SELECT_MEMBER";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const START_CHANGE_USER_ROLE = "START_CHANGE_USER_ROLE";
export const ADD_ROLE_USER_SUCCESS = "ADD_ROLE_USER_SUCCESS";
export const DELETE_ROLE_USER_SUCCESS = "DELETE_ROLE_USER_SUCCESS";

// * WEEEK ACTION TYPE
export const GET_CURRENT_WEEK = "GET_CURRENT_WEEK";
export const NEXT_WEEK = "NEXT_WEEK";
export const LAST_WEEK = "LAST_WEEK";
