// * AUTH ACTION TYPE
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SET_REDIRECT_PATH = "AUTH_SET_REDIRECT_PATH";
export const AUTH_LOGOUT = "AUTH_LOGIN";
export const AUTH_AUTHENTICATION = "AUTH_AUTHENTICATION";
export const AUTH_START_SIGN_UP = "AUTH_START_SIGN_UP";

// * PROJECT ACTION TYPE
export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";

// * TASK ACTION TYPE
export const FETCH_TASKS_START = "FETCH_TASKS_START";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAIL = "FETCH_TASKS_FAIL";
